### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by BertrandConxy** [kingqabil/book-an-appointment-backend#32]
### Team members

- Sadiq Habil
- Hamza Tarar
- Bertrand Mutangana

### Kanban Board

[Kanban Board link](https://github.com/kingqabil/book-an-appointment-backend/projects/1)

### Screenshot
![Final_kanban](https://user-images.githubusercontent.com/90222110/173905495-b88f89ce-1c2b-4322-b292-a00b7b2d74dc.png)

**NOTE: We started as a team of five but after some time, two members were removed due to the reasons we don't know. That is why we are doing the project as three.**

**Comment by MuriloRoque** [comment]
Hi @BertrandConxy, @Lockless404, @kingqabil,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [ ] Please put a screenshot of your Kanban board in this issue's description, just like it's mentioned in [the requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @BertrandConxy, @Lockless404, @kingqabil,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
